# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "FLIGHT" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"flightNumber" INTEGER NOT NULL,"airlineCode" VARCHAR NOT NULL,"airlineName" VARCHAR NOT NULL,"departureLocation" VARCHAR NOT NULL,"departureDay" INTEGER NOT NULL,"departureTime" INTEGER NOT NULL,"arrivalLocation" VARCHAR NOT NULL,"arrivalDay" INTEGER NOT NULL,"arrivalTime" INTEGER NOT NULL,"economyCost" INTEGER NOT NULL,"businessCost" INTEGER NOT NULL);
create table "USER" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"username" VARCHAR NOT NULL,"password" VARCHAR NOT NULL,"firstName" VARCHAR NOT NULL,"lastName" VARCHAR NOT NULL,"email" VARCHAR NOT NULL);
create unique index "unique_username" on "USER" ("username");

# --- !Downs

drop table "USER";
drop table "FLIGHT";

