
LOCK TABLES `airline` WRITE;
/*!40000 ALTER TABLE `airline` DISABLE KEYS */;

INSERT INTO `airline` (`id`, `iata`, `icao`, `airlineName`, `countryName`)
VALUES
	(1,'1T','RNX','1Time Airline','South Africa'),
	(2,'Q5','MLA','40-Mile Air','United States'),
	(3,'M3','TUS','ABSA - Aerolinhas Brasileiras','Brazil'),
	(4,'MO','AUH','Abu Dhabi Amiri Flight','United Arab Emirates'),
	(5,'ZA','CYD','Access Air','United States'),
	(6,'ZY','ADE','Ada Air','Albania'),
	(7,'KI','DHI','Adam Air','Indonesia'),
	(8,'JP','ADR','Adria Airways','Slovenia'),
	(9,'A3','AEE','Aegean Airlines','Greece'),
	(10,'RE','REA','Aer Arann','Ireland'),
	(11,'EI','EIN','Aer Lingus','Ireland'),
	(12,'JY','AXZ','Aereonautica militare','Italy'),
	(13,'EM','AEB','Aero Benin','Benin'),
	(14,'Q6','CDP','Aero Condor Peru','Peru'),
	(15,'AJ','NIG','Aero Contractors','Nigeria'),
	(16,'GV','ARF','Aero Flight','Germany'),
	(17,'QL','RLN','Aero Lanka','Sri Lanka'),
	(18,'BF','RSR','Aero-Service','Republic of the Congo'),
	(19,'2B','ARD','Aerocondor','Portugal'),
	(20,'SU','AFL','Aeroflot Russian Airlines','Russia'),
	(21,'D9','DNV','Aeroflot-Don','Russia'),
	(22,'5N','AUL','Aeroflot-Nord','Russia'),
	(23,'XL','LNE','Aerolane','Ecuador'),
	(24,'7E','AWU','Aeroline GmbH','Germany'),
	(25,'AR','ARG','Aerolineas Argentinas','Argentina'),
	(26,'2K','GLG','Aerolineas Galapagos (Aerogal)','Ecuador'),
	(27,'5D','SLI','Aerolitoral','Mexico'),
	(28,'VW','TAO','Aeromar','Mexico'),
	(29,'AM','AMX','AeroMéxico','Mexico'),
	(30,'OT','PEL','Aeropelican Air Services','Australia'),
	(31,'PL','PLI','Aeroper','Peru'),
	(32,'P5','RPB','AeroRep','Colombia'),
	(33,'5L','RSU','Aerosur','Bolivia'),
	(34,'VV','AEW','Aerosvit Airlines','Ukraine'),
	(35,'W4','WER','AeroWorld ','Russia'),
	(36,'FK','WTA','Africa West','Togo'),
	(37,'8U','AAW','Afriqiyah Airways','Libya'),
	(38,'ZI','AAF','Aigle Azur','France'),
	(39,'RK','RKA','Air Afrique','Ivory Coast'),
	(40,'AH','DAH','Air Algerie','Algeria'),
	(41,'G9','ABY','Air Arabia','United Arab Emirates'),
	(42,'E5','RBG','Air Arabia Egypt','Egypt'),
	(43,'KC','KZR','Air Astana','Kazakhstan'),
	(44,'CC','ABD','Air Atlanta Icelandic','Iceland'),
	(45,'UU','REU','Air Austral','France'),
	(46,'W9','JAB','Air Bagan','Myanmar'),
	(47,'BT','BTI','Air Baltic','Latvia'),
	(48,'B9','BGD','Air Bangladesh','Bangladesh'),
	(49,'AB','BER','Air Berlin','Germany'),
	(50,'JA','BON','Air Bosna','Bosnia and Herzegovina'),
	(51,'BP','BOT','Air Botswana','Botswana'),
	(52,'ZB','BUB','Air Bourbon','Reunion'),
	(53,'2J','VBW','Air Burkina','Burkina Faso'),
	(54,'BX','ABL','Air Busan','Republic of Korea'),
	(55,'SB','ACI','Air Caledonie International','France'),
	(56,'AC','ACA','Air Canada','Canada'),
	(57,'QK','JZA','Air Canada Jazz','Canada'),
	(58,'TX','FWI','Air Caraïbes','France'),
	(59,'2Q','SNC','Air Cargo Carriers','United States'),
	(60,'CV','CVA','Air Chathams','New Zealand'),
	(61,'CA','CCA','Air China','China'),
	(62,'EN','DLA','Air Dolomiti','Italy'),
	(63,'UX','AEA','Air Europa','Spain'),
	(64,'PE','AEL','Air Europe','Italy'),
	(65,'XT','AXL','Air Exel','Netherlands'),
	(66,'OF','FIF','Air Finland','Finland'),
	(67,'QH','FLZ','Air Florida','United States'),
	(68,'GS','UPA','Air Foyle','United Kingdom'),
	(69,'AF','AFR','Air France','France'),
	(70,'7T','AGV','Air Glaciers','Switzerland'),
	(71,'GL','GRL','Air Greenland','Denmark'),
	(72,'2U','GIP','Air Guinee Express','Guinea'),
	(73,'GG','GUY','Air Guyane','French Guiana'),
	(74,'HH','AHO','Air Hamburg (AHO)','Germany'),
	(75,'NY','FXI','Air Iceland','Iceland'),
	(76,'IX','AXB','Air India Express','India'),
	(77,'AI','AIC','Air India Limited','India'),
	(78,'PP','AI0','Air Indus','Pakistan'),
	(79,'I9','AEY','Air Italy','Italy'),
	(80,'VU','VUN','Air Ivoire','Ivory Coast'),
	(81,'JM','AJM','Air Jamaica','Jamaica'),
	(82,'NQ','AJX','Air Japan','Japan'),
	(83,'9Y','KZK','Air Kazakhstan','Kazakhstan'),
	(84,'4A','AKL','Air Kiribati','Kiribati'),
	(85,'JS','KOR','Air Koryo','Democratic People\'s Republic of Korea'),
	(86,'LK','LXR','Air Luxor','Portugal'),
	(87,'NX','AMU','Air Macau','Macao'),
	(88,'MD','MDG','Air Madagascar','Madagascar'),
	(89,'NM','DRD','Air Madrid','Spain'),
	(90,'QM','AML','Air Malawi','Malawi'),
	(91,'KM','AMC','Air Malta','Malta'),
	(92,'CW','CWM','Air Marshall Islands','Marshall Islands'),
	(93,'MK','MAU','Air Mauritius','Mauritius'),
	(94,'DR','BIE','Air Mediterranee','France'),
	(95,'P8','MKG','Air Mekong','Vietnam'),
	(96,'9U','MLD','Air Moldova','Moldova'),
	(97,'SW','NMB','Air Namibia','Namibia'),
	(98,'NZ','ANZ','Air New Zealand','New Zealand'),
	(99,'EL','ANK','Air Nippon','Japan'),
	(100,'PX','ANG','Air Niugini','Papua New Guinea'),
	(101,'4N','ANT','Air North Charter - Canada','Canada'),
	(102,'YW','ANE','Air Nostrum','Spain'),
	(103,'AP','ADH','Air One','Italy'),
	(104,'FJ','FJI','Air Pacific','Fiji'),
	(105,'2P','GAP','Air Philippines','Philippines'),
	(106,'A7','MPD','Air Plus Comet','Spain'),
	(107,'GZ','RAR','Air Rarotonga','Cook Islands'),
	(108,'S2','RSH','Air Sahara','India'),
	(109,'PJ','SPM','Air Saint Pierre','France'),
	(110,'HM','SEY','Air Seychelles','Seychelles'),
	(111,'4D','ASD','Air Sinai','Egypt'),
	(112,'VT','VTA','Air Tahiti','French Polynesia'),
	(113,'TN','THT','Air Tahiti Nui','France'),
	(114,'TC','ATC','Air Tanzania','Tanzania'),
	(115,'TS','TSC','Air Transat','Canada'),
	(116,'NF','AVN','Air Vanuatu','Vanuatu'),
	(117,'VL','VIM','Air VIA','Bulgaria'),
	(118,'6G','AWW','Air Wales','United Kingdom'),
	(119,'ZW','AWI','Air Wisconsin','United States'),
	(120,'UM','AZW','Air Zimbabwe','Zimbabwe'),
	(121,'AK','AXM','AirAsia','Malaysia'),
	(122,'D7','XAX','AirAsia X','Malaysia'),
	(123,'ED','ABQ','Airblue','Pakistan'),
	(124,'R3','SYL','Aircompany Yakutia','Russia'),
	(125,'4C','ARE','Aires',' S.A.'),
	(126,'A5','RLA','Airlinair','France'),
	(127,'FO','ATM','Airlines Of Tasmania','Australia'),
	(128,'CG','TOK','Airlines PNG','Papua New Guinea'),
	(129,'TL','ANO','Airnorth','Australia'),
	(130,'R8','RRJ','AirRussia','Russia'),
	(131,'FL','TRS','AirTran Airways','United States'),
	(132,'AS','ASA','Alaska Airlines','ALASKA'),
	(133,'KO','AER','Alaska Central Express','United States'),
	(134,'LV','LBC','Albanian Airlines','Albania'),
	(135,'AZ','AZA','Alitalia','Italy'),
	(136,'XM','SMX','Alitalia Express','Italy'),
	(137,'9A','99F','All Africa','South Africa'),
	(138,'A2','AL2','All America','United States'),
	(139,'L1','AL1','All Argentina','Argentina'),
	(140,'L9','AL3','All Asia','China'),
	(141,'7O','7KK','All Colombia','Colombia'),
	(142,'N9','N99','All Europe','United Kingdom'),
	(143,'NH','ANA','All Nippon Airways','Japan'),
	(144,'N7','N77','All Spain','Spain'),
	(145,'G4','AAY','Allegiant Air','United States'),
	(146,'QQ','UTY','Alliance Airlines','Australia'),
	(147,'UJ','LMU','AlMasria Universal Airlines','Egypt'),
	(148,'AQ','AAH','Aloha Airlines','United States'),
	(149,'6R','DRU','Alrosa Mirny Air Enterprise','Russia'),
	(150,'Z8','AZN','Amaszonas','Bolivia'),
	(151,'HP','AWE','America West Airlines','United States'),
	(152,'AA','AAL','American Airlines','United States'),
	(153,'MQ','EGF','American Eagle Airlines','United States'),
	(154,'WD','AAN','Amsterdam Airlines','Netherlands'),
	(155,'AN','AAA','Ansett Australia','Australia'),
	(156,'ZM','IWA','Apache Air','United States'),
	(157,'FG','AFG','Ariana Afghan Airlines','Afghanistan'),
	(158,'Q9','NAK','Arik Niger','Niger'),
	(159,'OR','TFL','Arkefly','Netherlands'),
	(160,'IZ','AIZ','Arkia Israel Airlines','Israel'),
	(161,'U8','RNV','Armavia','Armenia'),
	(162,'JW','APW','Arrow Air','United States'),
	(163,'R7','OCA','Aserca Airlines','Venezuela'),
	(164,'Y5','AWA','Asia Wings','Kazakhstan'),
	(165,'6K','RIT','Asian Spirit','Philippines'),
	(166,'AW','AWM','Asian Wings Airways','Burma'),
	(167,'OZ','AAR','Asiana Airlines','Republic of Korea'),
	(168,'4K','AAS','Askari Aviation','Pakistan'),
	(169,'5W','AEU','Astraeus','United Kingdom'),
	(170,'OB','ASZ','Astrakhan Airlines','Russia'),
	(171,'8V','ACP','Astral Aviation','Kenya'),
	(172,'A1','A1F','Atifly','United States'),
	(173,'3G','AYZ','Atlant-Soyuz Airlines','Russia'),
	(174,'RC','FLI','Atlantic Airways','Faroe Islands'),
	(175,'EV','ASQ','Atlantic Southeast Airlines','United States'),
	(176,'TD','LUR','Atlantis European Airways','Armenia'),
	(177,'5Y','GTI','Atlas Air','United States'),
	(178,'8A','BMM','Atlas Blue','Morocco'),
	(179,'KK','KKK','Atlasjet','Turkey'),
	(180,'V8','VAS','ATRAN Cargo Airlines','Russian Federation'),
	(181,'IQ','AUB','Augsburg Airways','Germany'),
	(182,'GR','AUR','Aurigny Air Services','United Kingdom'),
	(183,'AU','AUT','Austral Lineas Aereas','Argentina'),
	(184,'OS','AUA','Austrian Airlines','Austria'),
	(185,'U1','ABI','Aviabus','Russia'),
	(186,'EC','TWN','Avialeasing Aviation Company','Uzbekistan'),
	(187,'AV','AVA','Avianca - Aerovias Nacionales de Colombia','AVIANCA'),
	(188,'Z3','SMJ','Avient Aviation','Zimbabwe'),
	(189,'U3','AIA','Avies','Estonia'),
	(190,'J2','AHY','Azerbaijan Airlines','Azerbaijan'),
	(191,'AD','AZU','Azul','Brazil'),
	(192,'CJ','CFE','BA CityFlyer','United Kingdom'),
	(193,'UP','BHS','Bahamasair','Bahamas'),
	(194,'BU','BUU','Baikotovitchestrian Airlines ','American Samoa'),
	(195,'B1','BA1','Baltic Air lines','Latvia'),
	(196,'PG','BKP','Bangkok Airways','Thailand'),
	(197,'8N','NKF','Barents AirLink','Sweden'),
	(198,'JV','BLS','Bearskin Lake Air Service','Canada'),
	(199,'4T','BHP','Belair Airlines','Switzerland'),
	(200,'B2','BRU','Belavia Belarusian Airlines','Belarus'),
	(201,'B3','BLV','Bellview Airlines','Nigeria'),
	(202,'CH','BMJ','Bemidji Airlines','United States'),
	(203,'8E','BRG','Bering Air','United States'),
	(204,'J8','BVT','Berjaya Air','Malaysia'),
	(205,'BG','BBC','Biman Bangladesh Airlines','Bangladesh'),
	(206,'NT','IBB','Binter Canarias','Spain'),
	(207,'BZ','BSA','Black Stallion Airways','United States'),
	(208,'0B','JOR','Blue Air','Romania'),
	(209,'BV','BPA','Blue Panorama Airlines','Italy'),
	(210,'QW','BWG','Blue Wings','Germany'),
	(211,'KF','BLF','Blue1','Finland'),
	(212,'BD','BMA','bmi','United Kingdom'),
	(213,'WW','BMI','bmibaby','United Kingdom'),
	(214,'GB','BZE','BRAZIL AIR','Brazil'),
	(215,'DB','BZH','Brit Air','France'),
	(216,'BA','BAW','British Airways','United Kingdom'),
	(217,'BS','BIH','British International Helicopters','United Kingdom'),
	(218,'KJ','LAJ','British Mediterranean Airways','United Kingdom'),
	(219,'SN','DAT','Brussels Airlines','Belgium'),
	(220,'FB','LZB','Bulgaria Air','Bulgaria'),
	(221,'BQ','BQB','Buquebus Líneas Aéreas','Uruguay'),
	(222,'8B','BCC','BusinessAir','Thailand'),
	(223,'5C','ICL','CAL Cargo Air Lines','Israel'),
	(224,'XG','CLI','Calima Aviacion','Spain'),
	(225,'CP','CDN','Canadian Airlines','Canada'),
	(226,'CN','YCP','Canadian National Airways','Canada'),
	(227,'5T','MPE','Canadian North','Canada'),
	(228,'C2','CAP','CanXplorer','Canada'),
	(229,'C1','CA1','CanXpress','Canada'),
	(230,'9K','KAP','Cape Air','United States'),
	(231,'8L','CGP','Cargo Plus Aviation','United Arab Emirates'),
	(232,'BW','BWA','Caribbean Airlines','Trinidad and Tobago'),
	(233,'V3','KRP','Carpatair','Romania'),
	(234,'RV','CPN','Caspian Airlines','Iran'),
	(235,'CX','CPA','Cathay Pacific','Hong Kong SAR of China'),
	(236,'KX','CAY','Cayman Airways','Cayman Islands'),
	(237,'1F','CIF','CB Airways UK ( Interliging Flights )','United Kingdom'),
	(238,'CB','CCC','CCML Airlines','Colombia'),
	(239,'5J','CEB','Cebu Pacific','Philippines'),
	(240,'C0','CLW','Centralwings','Poland'),
	(241,'RP','CHQ','Chautauqua Airlines','United States'),
	(242,'CI','CAL','China Airlines','Taiwan'),
	(243,'MU','CES','China Eastern Airlines','China'),
	(244,'CZ','CSN','China Southern Airlines','China'),
	(245,'HR','CUA','China United Airlines','China'),
	(246,'OQ','CQN','Chongqing Airlines','China'),
	(247,'YC','YCC','Ciel Canadien','Canada'),
	(248,'QI','CIM','Cimber Air','Denmark'),
	(249,'C9','RUS','Cirrus Airlines','Germany'),
	(250,'CF','SDR','City Airline','Sweden'),
	(251,'G3','CIX','City Connexion Airlines','Burundi'),
	(252,'WX','BCY','CityJet','Ireland'),
	(253,'9L','CJC','Colgan Air','United States'),
	(254,'MN','CAW','Comair','South Africa'),
	(255,'OH','COM','Comair','United States'),
	(256,'C5','UCA','CommutAir','United States'),
	(257,'KR','CWK','Comores Airlines','Comoros'),
	(258,'CP','CPZ','Compass Airlines','United States'),
	(259,'DE','CFG','Condor Flugdienst','Germany'),
	(260,'6A','CHP','Consorcio Aviaxsa','Mexico'),
	(261,'C3','KIS','Contact Air','Germany'),
	(262,'CO','COA','Continental Airlines','United States'),
	(263,'CS','CMI','Continental Micronesia','United States'),
	(264,'V0','VCV','Conviasa','Venezuela'),
	(265,'CM','CMP','Copa Airlines','Panama'),
	(266,'0X','CX0','Copenhagen Express','Denmark'),
	(267,'SS','CRL','Corsairfly','France'),
	(268,'XK','CCM','Corse-Mediterranee','France'),
	(269,'OU','CTN','Croatia Airlines','Croatia'),
	(270,'CU','CUB','Cubana de Aviación','Cuba'),
	(271,'CY','CYP','Cyprus Airways','Cyprus'),
	(272,'OK','CSA','Czech Airlines','Czech Republic'),
	(273,'D3','DAO','Daallo Airlines','Djibouti'),
	(274,'H8','KHB','Dalavia','Russia'),
	(275,'0D','DWT','Darwin Airline','Switzerland'),
	(276,'DX','DTR','DAT Danish Air Transport','Denmark'),
	(277,'DI','BAG','dba','Germany'),
	(278,'DL','DAL','Delta Air Lines','United States'),
	(279,'DH','DSY','Dennis Sky','Israel'),
	(280,'D8','DJB','Djibouti Airlines','Djibouti'),
	(281,'QD','DOB','Dobrolet','Russia'),
	(282,'D1','MDO','Domenican Airlines','Dominican Republic'),
	(283,'DO','DOA','Dominicana de Aviaci','Dominican Republic'),
	(284,'E3','DMO','Domodedovo Airlines','Russia'),
	(285,'5D','UDC','DonbassAero','Ukraine'),
	(286,'KA','HDA','Dragonair','DRAGON'),
	(287,'KB','DRK','Druk Air','Bhutan'),
	(288,'QU','UGX','East African','Uganda'),
	(289,'ZE','ESR','Eastar Jet','South Korea'),
	(290,'T3','EZE','Eastern Airways','United Kingdom'),
	(291,'DK','ELA','Eastland Air','Australia'),
	(292,'U2','EZY','easyJet','United Kingdom'),
	(293,'WK','EDW','Edelweiss Air','Switzerland'),
	(294,'MS','MSR','Egyptair','Egypt'),
	(295,'LY','ELY','El Al Israel Airlines','Israel'),
	(296,'UZ','BRQ','El-Buraq Air Transport','Libya'),
	(297,'E4','GIE','Elysian Airlines','Cameroon'),
	(298,'EK','UAE','Emirates','United Arab Emirates'),
	(299,'EU','EEA','Empresa Ecuatoriana De Aviacion','Ecuador'),
	(300,'FA','4AA','Epic Holiday','United States'),
	(301,'7H','ERR','Era Alaska','United States'),
	(302,'B8','ERT','Eritrean Airlines','Eritrea'),
	(303,'OV','ELL','Estonian Air','Estonia'),
	(304,'ET','ETH','Ethiopian Airlines','Ethiopia'),
	(305,'EY','ETD','Etihad Airways','United Arab Emirates'),
	(306,'UI','ECA','Eurocypria Airlines','Cyprus'),
	(307,'GJ','EEU','Eurofly Service','Italy'),
	(308,'4L','MJX','Euroline','Georgia'),
	(309,'K2','ELO','Eurolot','Poland'),
	(310,'EA','EAL','European Air Express','Germany'),
	(311,'ES','EUV','EuropeSky','Germany'),
	(312,'EW','EWG','Eurowings','Germany'),
	(313,'BR','EVA','EVA Air','Taiwan'),
	(314,'EZ','EIA','Evergreen International Airlines','United States'),
	(315,'JN','XLA','Excel Airways','United Kingdom'),
	(316,'EO','LHN','Express One International','United States'),
	(317,'XE','BTA','ExpressJet','United States'),
	(318,'EF','EFA','Far Eastern Air Transport','Taiwan'),
	(319,'FU','FXX','Felix Airways','Yemen'),
	(320,'AY','FIN','Finnair','Finland'),
	(321,'FC','WBA','Finncomm Airlines','Finland'),
	(322,'FY','FFM','Firefly','Malaysia'),
	(323,'7F','FAB','First Air','Canada'),
	(324,'DP','FCA','First Choice Airways','United Kingdom'),
	(325,'B5','FLT','Flightline','United Kingdom'),
	(326,'RF','FWL','Florida West International Airways','United States'),
	(327,'F1','FBL','Fly Brasil','Brazil'),
	(328,'3F','3FF','Fly Colombia ( Interliging Flights )','Colombia'),
	(329,'FZ','FDB','Fly Dubai','United Arab Emirates'),
	(330,'ER','RWW','Fly Europa','Spain'),
	(331,'5H','FFV','Fly540','Kenya'),
	(332,'F7','BBO','Flybaboo','Switzerland'),
	(333,'BE','BEE','Flybe','United Kingdom'),
	(334,'B4','GSM','Flyglobespan','United Kingdom'),
	(335,'FH','FHI','FlyHigh Airlines Ireland (FH)','Ireland'),
	(336,'TE','LIL','FlyLal','Lithuania'),
	(337,'LF','NDC','FlyNordic','Sweden'),
	(338,'PO','FPT','FlyPortugal','Portugal'),
	(339,'VY','FOS','Formosa Airlines','Taiwan'),
	(340,'FP','FRE','Freedom Air','United States'),
	(341,'F9','FFT','Frontier Airlines','United States'),
	(342,'2F','FTA','Frontier Flying Service','United States'),
	(343,'GY','GBK','Gabon Airlines','Gabon'),
	(344,'GP','GDR','Gadair European Airlines','Spain'),
	(345,'GA','GIA','Garuda Indonesia','Indonesia'),
	(346,'4G','GZP','Gazpromavia','Russia'),
	(347,'GT','GBL','GB Airways','United Kingdom'),
	(348,'A9','TGZ','Georgian Airways','Georgia'),
	(349,'QB','GFG','Georgian National Airlines','Georgia'),
	(350,'GM','GER','German International Air Lines','Germany'),
	(351,'ST','GMI','Germania','Germany'),
	(352,'4U','GWI','Germanwings','Germany'),
	(353,'G0','GHB','Ghana International Airlines','Ghana'),
	(354,'GH','GLP','Globus','Russia'),
	(355,'G8','GOW','Go Air','India'),
	(356,'G7','GJS','GoJet Airlines','United States'),
	(357,'G3','GLO','Gol Transportes Aéreos','Brazil'),
	(358,'DC','GAO','Golden Air','Sweden'),
	(359,'ZK','GLA','Great Lakes Airlines','United States'),
	(360,'XX','GFY','Greenfly','Spain'),
	(361,'TA','TAT','Grupo TACA','Costa Rica'),
	(362,'GF','GBA','Gulf Air Bahrain','Bahrain'),
	(363,'H6','HAG','Hageland Aviation Services','United States'),
	(364,'HU','CHH','Hainan Airlines','China'),
	(365,'2T','HAM','Haiti Ambassador Airlines','Haiti'),
	(366,'4R','HHI','Hamburg International','Germany'),
	(367,'H1','HA1','Hankook Air US','United States'),
	(368,'HN','HNX','Hankook Airline','South Korea'),
	(369,'HF','HLF','Hapagfly','Germany'),
	(370,'HA','HAL','Hawaiian Airlines','United States'),
	(371,'8H','HFR','Heli France','France'),
	(372,'JB','JBA','Helijet','Canada'),
	(373,'T4','HEJ','Hellas Jet','Greece'),
	(374,'HT','IMP','Hellenic Imperial Airways','Greece'),
	(375,'HW','FHE','Hello','Switzerland'),
	(376,'2L','OAW','Helvetic Airways','Switzerland'),
	(377,'UD','HER','Hex\'Air','France'),
	(378,'HC','HYM','Himalayan Airlines','Nepal'),
	(379,'HD','ADO','Hokkaido International Airlines','Japan'),
	(380,'MR','OME','Homer Air','Germany'),
	(381,'HX','CRK','Hong Kong Airlines','Hong Kong SAR of China'),
	(382,'UO','HKE','Hong Kong Express Airways','Hong Kong SAR of China'),
	(383,'QX','QXE','Horizon Air','United States'),
	(384,'BN','HZA','Horizon Airlines','Australia'),
	(385,'H5','RSY','I-Fly','Russia'),
	(386,'IB','IBE','Iberia Airlines','Spain'),
	(387,'I2','IBS','Iberia Express','Spain'),
	(388,'TY','IWD','Iberworld','Spain'),
	(389,'FW','IBX','Ibex Airlines','Japan'),
	(390,'FI','ICE','Icelandair','Iceland'),
	(391,'IK','ITX','Imair Airlines','Azerbaijan'),
	(392,'IC','IAC','Indian Airlines','India'),
	(393,'I9','IBU','Indigo','United States'),
	(394,'6E','IGO','IndiGo Airlines','India'),
	(395,'QZ','AWQ','Indonesia AirAsia','Indonesia'),
	(396,'I5','IDS','Indonesia Sky','Indonesia'),
	(397,'IO','IAA','Indonesian Airlines','Indonesia'),
	(398,'G1','IG1','Indya Airline Group','India'),
	(399,'D6','ILN','Interair South Africa','South Africa'),
	(400,'ZA','SUW','Interavia Airlines','Russia'),
	(401,'ID','ITK','Interlink Airlines','South Africa'),
	(402,'3L','ISK','Intersky','Austria'),
	(403,'IR','IRA','Iran Air','Iran'),
	(404,'EP','IRC','Iran Aseman Airlines','Iran'),
	(405,'IA','IAW','Iraqi Airways','Iraq'),
	(406,'WP','MKU','Island Air (WP)','United States'),
	(407,'IP','ISX','Island Spirit','Iceland'),
	(408,'IF','ISW','Islas Airways','Spain'),
	(409,'WC','ISV','Islena De Inversiones','Honduras'),
	(410,'6H','ISR','Israir','Israel'),
	(411,'GI','IKA','Itek Air','Kyrgyzstan'),
	(412,'JC','JEX','JAL Express','Japan'),
	(413,'JO','JAZ','JALways','Japan'),
	(414,'JD','JAS','Japan Air System','Japan'),
	(415,'JL','JAL','Japan Airlines','Japan'),
	(416,'JL','JAL','Japan Airlines Domestic','Japan'),
	(417,'EG','JAA','Japan Asia Airways','Japan'),
	(418,'ZX','ZXY','Japan Regio','Japan'),
	(419,'NU','JTA','Japan Transocean Air','Japan'),
	(420,'JU','JAT','Jat Airways','Serbia'),
	(421,'J9','JZR','Jazeera Airways','Kuwait'),
	(422,'7C','JJA','Jeju Air','Republic of Korea'),
	(423,'9W','JAI','Jet Airways','India'),
	(424,'LS','EXS','Jet2.com','United Kingdom'),
	(425,'8J','JFU','Jet4You','Morocco'),
	(426,'JF','JAF','Jetairfly','Belgium'),
	(427,'B6','JBU','JetBlue Airways','United States'),
	(428,'JQ','JST','Jetstar Airways','Australia'),
	(429,'3K','JSA','Jetstar Asia Airways','Singapore'),
	(430,'BL','PIC','Jetstar Pacific','Vietnam'),
	(431,'NR','JTO','Jettor Airlines','Hong Kong'),
	(432,'LJ','JNA','Jin Air','South Korea'),
	(433,'JR','JOY','Joy Air','China'),
	(434,'HO','DKH','Juneyao Airlines','China'),
	(435,'JX','JSR','Jusur airways','Egypt'),
	(436,'RQ','KMF','Kam Air','Afghanistan'),
	(437,'KV','MVD','Kavminvodyavia','Russia'),
	(438,'KD','KNI','KD Avia','Russia'),
	(439,'M5','KEN','Kenmore Air','United States'),
	(440,'KQ','KQA','Kenya Airways','Kenya'),
	(441,'KH','KHK','Kharkiv Airlines','Ukraine'),
	(442,'IT','KFR','Kingfisher Airlines','India'),
	(443,'Y9','IRK','Kish Air','Iran'),
	(444,'WA','KLC','KLM Cityhopper','Netherlands'),
	(445,'KL','KLM','KLM Royal Dutch Airlines','Netherlands'),
	(446,'7K','KGL','Kogalymavia Air Company','Russia'),
	(447,'K7','KBR','KoralBlue Airlines','Egypt'),
	(448,'KE','KAL','Korean Air','Republic of Korea'),
	(449,'ZC','KGO','Korongo Airlines','Congo (Kinshasa)'),
	(450,'K1','KOQ','Kostromskie avialinii','Russia'),
	(451,'7B','KJC','Krasnojarsky Airlines','Russia'),
	(452,'KY','KSY','KSY','Greece'),
	(453,'GW','KIL','Kuban Airlines','Russia'),
	(454,'KU','KAC','Kuwait Airways','Kuwait'),
	(455,'GO','KZU','Kuzu Airlines Cargo','Turkey'),
	(456,'MJ','LPR','L','Argentina'),
	(457,'LR','LRC','LACSA','Costa Rica'),
	(458,'LA','LAN','LAN Airlines','Chile'),
	(459,'4M','DSM','LAN Argentina','Argentina'),
	(460,'LU','LXP','LAN Express','Chile'),
	(461,'LP','LPE','LAN Peru','Peru'),
	(462,'QV','LAO','Lao Airlines','Lao Peoples Democratic Republic'),
	(463,'NG','LDA','Lauda Air','Austria'),
	(464,'LQ','LMM','LCM AIRLINES','Russia'),
	(465,'LI','LIA','Leeward Islands Air Transport','Antigua and Barbuda'),
	(466,'LN','LAA','Libyan Arab Airlines','Libya'),
	(467,'L8','LBL','Line Blue','Germany'),
	(468,'LM','LAM','Linhas A','Mozambique'),
	(469,'JT','LNI','Lion Mentari Airlines','Indonesia'),
	(470,'C4','LIX','LionXpress','Cameroon'),
	(471,'ZQ','LOC','Locair','United States'),
	(472,'LO','LOT','LOT Polish Airlines','Poland'),
	(473,'PQ','LOO','LSM Airlines','Russia'),
	(474,'YZ','YZZ','LSM AIRLINES ','Russia'),
	(475,'II','UWW','LSM International ','Russia'),
	(476,'XO','LTE','LTE International Airways','Spain'),
	(477,'L3','LTO','LTU Austria','Austria'),
	(478,'LT','LTU','LTU International','Germany'),
	(479,'L4','LJJ','Luchsh Airlines ','Russia'),
	(480,'HE','LGW','Luftfahrtgesellschaft Walter','Germany'),
	(481,'LH','DLH','Lufthansa','Germany'),
	(482,'LH','GEC','Lufthansa Cargo','Germany'),
	(483,'CL','CLH','Lufthansa CityLine','Germany'),
	(484,'L5','LTR','Lufttransport','Norway'),
	(485,'LG','LGL','Luxair','Luxembourg'),
	(486,'CC','MCK','Macair Airlines','Australia'),
	(487,'W5','IRM','Mahan Air','Iran'),
	(488,'MH','MAS','Malaysia Airlines','Malaysia'),
	(489,'ML','MAV','Maldivo Airlines','Maldives'),
	(490,'MA','MAH','Malév','Hungary'),
	(491,'OD','MXD','Malindo Air','Malaysia'),
	(492,'TF','SCW','Malmö Aviation','Sweden'),
	(493,'R5','MAC','Malta Air Charter','Malta'),
	(494,'RI','MDL','Mandala Airlines','Indonesia'),
	(495,'AE','MDA','Mandarin Airlines','Taiwan'),
	(496,'JE','MNO','Mango','South Africa'),
	(497,'MP','MPH','Martinair','Netherlands'),
	(498,'Y8','MRS','Marusya Airways','Russia'),
	(499,'M1','M1F','Maryland Air','United States'),
	(500,'M4','1QA','Marysya Airlines','Russia'),
	(501,'M7','MAA','MasAir','Mexico'),
	(502,'6F','MKD','MAT Airways','Macedonia'),
	(503,'IN','MAK','MAT Macedonian Airlines','Macedonia'),
	(504,'L6','MAI','Mauritania Airlines International','Mauritania'),
	(505,'8M','MXL','Maxair','Sweden'),
	(506,'MW','MYD','Maya Island Air','Belize'),
	(507,'IG','ISS','Meridiana','Italy'),
	(508,'MZ','MNA','Merpati Nusantara Airlines','Indonesia'),
	(509,'YV','ASH','Mesa Airlines','United States'),
	(510,'XJ','MES','Mesaba Airlines','United States'),
	(511,'7P','BTV','Metro Batavia','Indonesia'),
	(512,'MX','MXA','Mexicana de Aviaci','Mexico'),
	(513,'I6','MXI','MexicanaLink','Mexico'),
	(514,'OM','MGL','MIAT Mongolian Airlines','Mongolia'),
	(515,'DF','MJG','Michael Airlines','Puerto Rico'),
	(516,'ME','MEA','Middle East Airlines','Lebanon'),
	(517,'JI','MDW','Midway Airlines','United States'),
	(518,'YX','MEP','Midwest Airlines','United States'),
	(519,'MY','MWA','Midwest Airlines (Egypt)','Egypt'),
	(520,'MB','MNB','MNG Airlines','Turkey'),
	(521,'2M','MDV','Moldavian Airlines','Moldova'),
	(522,'ZB','MON','Monarch Airlines','United Kingdom'),
	(523,'7M','ZTF','Mongolian International Air Lines ','Mongolia'),
	(524,'YM','MGX','Montenegro Airlines','Montenegro'),
	(525,'3R','GAI','Moskovia Airlines','Russia'),
	(526,'M9','MSI','Motor Sich','Ukraine'),
	(527,'UB','UBA','Myanma Airways','Myanmar'),
	(528,'8M','MMM','Myanmar Airways International','Myanmar'),
	(529,'VZ','MYT','MyTravel Airways','United Kingdom'),
	(530,'XY','KNE','Nas Air','Saudi Arabia'),
	(531,'UE','NAS','Nasair','Eritrea'),
	(532,'N8','NCR','National Air Cargo','United States'),
	(533,'NC','NJS','National Jet Systems','Australia'),
	(534,'CE','NTW','Nationwide Airlines','South Africa'),
	(535,'ON','RON','Nauru Air Corporation','Nauru'),
	(536,'RA','RNA','Nepal Airlines','Nepal'),
	(537,'1I','EJA','NetJets','United States'),
	(538,'EJ','NEA','New England Airlines','United States'),
	(539,'XB','NXB','NEXT Brasil','Brazil'),
	(540,'2N','NTJ','NextJet','Sweden'),
	(541,'HG','NLY','Niki','Austria'),
	(542,'NP','NIA','Nile Air','Egypt'),
	(543,'DD','NOK','Nok Air','Thailand'),
	(544,'NJ','NGB','Nordic Global Airlines','Finland'),
	(545,'NW','NWA','Northwest Airlines','United States'),
	(546,'J3','PLR','Northwestern Air','Canada'),
	(547,'DY','NAX','Norwegian Air Shuttle','Norway'),
	(548,'BJ','LBT','Nouvel Air Tunisie','Tunisia'),
	(549,'1I','NVR','Novair','Sweden'),
	(550,'O8','OHK','Oasis Hong Kong Airlines','Hong Kong'),
	(551,'O6','ONE','Oceanair','Brazil'),
	(552,'OA','OAL','Olympic Airlines','Greece'),
	(553,'WY','OMA','Oman Air','Oman'),
	(554,'OY','OAE','Omni Air International','United States'),
	(555,'1C','1CH','OneChina','China'),
	(556,'8Q','OHY','Onur Air','Turkey'),
	(557,'O1','OAB','Orbit Airlines Azerbaijan','Azerbaijan'),
	(558,'OI','ORC','Orchid Airlines','Australia'),
	(559,'R2','ORB','Orenburg Airlines','Russia'),
	(560,'OX','OEA','Orient Thai Airlines','Thailand'),
	(561,'QO','OGN','Origin Pacific Airways','New Zealand'),
	(562,'OL','OLT','Ostfriesische Lufttransport','Germany'),
	(563,'OJ','OLA','Overland Airways','Nigeria'),
	(564,'O7','OZJ','Ozjet Airlines','Australia'),
	(565,'8P','PCO','Pacific Coastal Airline','Canada'),
	(566,'Q8','PEC','Pacific East Asia Cargo Airlines','Philippines'),
	(567,'LW','NMI','Pacific Wings','United States'),
	(568,'PK','PIA','Pakistan International Airlines','Pakistan'),
	(569,'PV','PNR','PAN Air','Spain'),
	(570,'WQ','PQW','PanAm World Airways','United States'),
	(571,'I7','PMW','Paramount Airways','India'),
	(572,'PA','IPV','Parmiss Airlines (IPV)','Iran'),
	(573,'9Q','PBA','PB Air','Thailand'),
	(574,'PC','PGT','Pegasus Airlines','Turkey'),
	(575,'KS','PEN','Peninsula Airways','United States'),
	(576,'PR','PAL','Philippine Airlines','Philippines'),
	(577,'PI','PDT','Piedmont Airlines (1948-1989)','United States'),
	(578,'9E','FLG','Pinnacle Airlines','United States'),
	(579,'PU','PUA','PLUNA','Uruguay'),
	(580,'U4','PMT','PMTair','Cambodia'),
	(581,'PH','PAO','Polynesian Airlines','Samoa'),
	(582,'PD','POE','Porter Airlines','Canada'),
	(583,'NI','PGA','Portugalia','Portugal'),
	(584,'BK','PDC','Potomac Air','United States'),
	(585,'PW','PRF','Precision Air','Tanzania'),
	(586,'QF','QFA','Qantas','Australia'),
	(587,'QR','QTR','Qatar Airways','Qatar'),
	(588,'C3','QAX','QatXpress','Qatar'),
	(589,'RN','RAB','Rainbow Air (RAI)','United States'),
	(590,'RY','RAY','Rainbow Air Canada','Canada'),
	(591,'RU','RUE','Rainbow Air Euro','United Kingdom'),
	(592,'RX','RPO','Rainbow Air Polynesia','United States'),
	(593,'RM','RNY','Rainbow Air US','United States'),
	(594,'WZ','RWZ','Red Wings','Russia'),
	(595,'YS','RAE','Régional','France'),
	(596,'9N','N78','Regional Air Iceland','Iceland'),
	(597,'ZL','RXA','Regional Express','Australia'),
	(598,'P7','REP','Regional Paraguaya','Paraguay'),
	(599,'9J','CR1','Regionalia Chile','Chile'),
	(600,'N4','J88','Regionalia México','Mexico'),
	(601,'2X','2K2','Regionalia Uruguay','Uruguay'),
	(602,'9X','9XX','Regionalia Venezuela','Venezuela'),
	(603,'RW','RPA','Republic Airlines','United States'),
	(604,'RH','RPH','Republic Express Airlines','Indonesia'),
	(605,'FV','SDM','Rossiya-Russian Airlines','Russia'),
	(606,'VJ','RAC','Royal Air Cambodge','Cambodia'),
	(607,'AT','RAM','Royal Air Maroc','Morocco'),
	(608,'KG','RAW','Royal Airways','United States'),
	(609,'BI','RBA','Royal Brunei Airlines','Brunei'),
	(610,'RL','RFJ','Royal Falcon','Jordan'),
	(611,'RJ','RJA','Royal Jordanian','Jordan'),
	(612,'RA','RNA','Royal Nepal Airlines','Nepal'),
	(613,'WB','RWD','Rwandair Express','Rwanda'),
	(614,'RD','RYN','Ryan International Airlines','United States'),
	(615,'FR','RYR','Ryanair','Ireland'),
	(616,'S7','SBI','S7 Airlines','Russia'),
	(617,'SO','SLC','Salsa d\\\\\'Haiti','Haiti'),
	(618,'ZS','SMY','Sama Airlines','Saudi Arabia'),
	(619,'S3','BBR','Santa Barbara Airlines','Venezuela'),
	(620,'6W','SOV','Saratov Aviation Division','Russia'),
	(621,'HZ','SOZ','Sat Airlines','Kazakhstan'),
	(622,'SP','SAT','SATA Air Acores','Portugal'),
	(623,'S4','RZO','SATA International','Portugal'),
	(624,'9R','NSE','SATENA','Colombia'),
	(625,'SV','SVA','Saudi Arabian Airlines','Saudi Arabia'),
	(626,'SK','SAS','Scandinavian Airlines System','Sweden'),
	(627,'DV','VSV','Scat Air','Kazakhstan'),
	(628,'TZ','SCO','Scoot','Singapore'),
	(629,'BB','SBS','Seaborne Airlines','United States'),
	(630,'K5','SQH','SeaPort Airlines','United States'),
	(631,'DN','SGG','Senegal Airlines','Senegal'),
	(632,'S1','SA1','Serbian Airlines','Serbia'),
	(633,'FS','STU','Servicios de Transportes A','Argentina'),
	(634,'NL','SAI','Shaheen Air International','Pakistan'),
	(635,'SC','CDG','Shandong Airlines','China'),
	(636,'FM','CSH','Shanghai Airlines','China'),
	(637,'SH','SHA','Sharp Airlines','Australia'),
	(638,'ZH','CSZ','Shenzhen Airlines','China'),
	(639,'S5','TCF','Shuttle America','United States'),
	(640,'5M','SIB','Sibaviatrans','Russia'),
	(641,'3U','CSC','Sichuan Airlines','China'),
	(642,'FT','SRH','Siem Reap Airways','Cambodia'),
	(643,'MI','SLK','SilkAir','Singapore'),
	(644,'SQ','SIA','Singapore Airlines','Singapore'),
	(645,'SQ','SQC','Singapore Airlines Cargo','Singapore'),
	(646,'N5','SGY','Skagway Air Service','United States'),
	(647,'H2','SKU','Sky Airline','Chile'),
	(648,'G3','SEH','Sky Express','Greece'),
	(649,'XW','SXR','Sky Express','Russia'),
	(650,'C7','CR7','Sky Wing Pacific','South Korea'),
	(651,'NE','ESK','SkyEurope','Slovakia'),
	(652,'UQ','SJU','Skyjet Airlines','Uganda'),
	(653,'BC','SKY','Skymark Airlines','Japan'),
	(654,'SI','SIH','Skynet Airlines','Ireland'),
	(655,'6J','SNJ','Skynet Asia Airways','Japan'),
	(656,'5G','SSV','Skyservice Airlines','Canada'),
	(657,'AL','SYX','Skywalk Airlines','United States'),
	(658,'JZ','SKX','Skyways Express','Sweden'),
	(659,'OO','SKW','SkyWest','United States'),
	(660,'S8','SBD','Snowbird Airlines','Finland'),
	(661,'CQ','KOL','SOCHI AIR','Russia'),
	(662,'Q3','QER','SOCHI AIR CHATER','Russia'),
	(663,'IE','SOL','Solomon Airlines','Solomon Islands'),
	(664,'SA','SAA','South African Airways','South Africa'),
	(665,'DG','SRQ','South East Asian Airlines','Philippines'),
	(666,'A4','SWD','Southern Winds Airlines','Argentina'),
	(667,'WN','SWA','Southwest Airlines','United States'),
	(668,'JK','JKK','Spanair','Spain'),
	(669,'SG','SEJ','Spicejet','India'),
	(670,'S0','SAL','Spike Airlines','United States'),
	(671,'NK','NKS','Spirit Airlines','United States'),
	(672,'SM','MNP','Spirit of Manila Airlines','Philippines'),
	(673,'9S','CQH','Spring Airlines','China'),
	(674,'UL','ALK','SriLankan Airlines','Sri Lanka'),
	(675,'SJ','SJY','Sriwijaya Air','Indonesia'),
	(676,'7G','SFJ','Star Flyer','Japan'),
	(677,'V9','HCW','Star1 Airlines','Lithuania'),
	(678,'NB','SNB','Sterling Airlines','Denmark'),
	(679,'8F','STP','STP Airways','Sao Tome and Principe'),
	(680,'SD','SUD','Sudan Airways','Sudan'),
	(681,'SY','SCX','Sun Country Airlines','United States'),
	(682,'7L','ERO','Sun D\'Or','Israel'),
	(683,'XQ','SXS','SunExpress','Turkey'),
	(684,'PY','SLM','Surinam Airways','Suriname'),
	(685,'WV','SWV','Swe Fly','Sweden'),
	(686,'LX','SWR','Swiss International Air Lines','Switzerland'),
	(687,'SR','SWR','Swissair','Switzerland'),
	(688,'RB','SYR','Syrian Arab Airlines','Syrian Arab Republic'),
	(689,'TJ','TJA','T.J. Air','United States'),
	(690,'DT','DTA','TAAG Angola Airlines','Angola'),
	(691,'VR','TCV','TACV','Portugal'),
	(692,'JJ','TAM','TAM Brazilian Airlines','Brazil'),
	(693,'PZ','LAP','TAM Mercosur','Paraguay'),
	(694,'EQ','TAE','TAME','Ecuador'),
	(695,'QT','TPA','TAMPA','Colombia'),
	(696,'TP','TAP','TAP Portugal','Portugal'),
	(697,'RO','ROT','Tarom','Romania'),
	(698,'U9','TAK','Tatarstan Airlines','Russia'),
	(699,'TQ','TXW','Texas Wings','United States'),
	(700,'T2','TCG','Thai Air Cargo','Thailand'),
	(701,'FD','AIQ','Thai AirAsia','Thailand'),
	(702,'TG','THA','Thai Airways International','Thailand'),
	(703,'FQ','TCW','Thomas Cook Airlines','Belgium'),
	(704,'MT','TCX','Thomas Cook Airlines','United Kingdom'),
	(705,'BY','TOM','Thomsonfly','United Kingdom'),
	(706,'3P','TNM','Tiara Air','Aruba'),
	(707,'TR','TGW','Tiger Airways','Singapore'),
	(708,'TT','TGW','Tiger Airways Australia','Australia'),
	(709,'TL','TMA','Trans Mediterranean Airlines','Lebanon'),
	(710,'T6','TP6','Trans Pas Air','United States'),
	(711,'AX','LOF','Trans States Airlines','United States'),
	(712,'UN','TSO','Transaero Airlines','Russia'),
	(713,'GE','TNA','TransAsia Airways','Taiwan'),
	(714,'TO','TVF','Transavia France','France'),
	(715,'HV','TRA','Transavia Holland','Netherlands'),
	(716,'TH','THS','TransBrasil Airlines','Brazil'),
	(717,'TI','THI','TransHolding','Brazil'),
	(718,'YO','TYS','TransHolding System','Brazil'),
	(719,'9T','ABS','Transwest Air','Canada'),
	(720,'TB','TBZ','TrasBrasil','Brazil'),
	(721,'QS','TVS','Travel Service','Czech Republic'),
	(722,'8R','TIB','TRIP Linhas A','Brazil'),
	(723,'PM','TOS','Tropic Air','Belize'),
	(724,'X3','HLX','TUIfly','Germany'),
	(725,'6B','BLX','TUIfly Nordic','Sweden'),
	(726,'UG','TUI','Tuninter','Tunisia'),
	(727,'TU','TAR','Tunisair','Tunisia'),
	(728,'3T','URN','Turan Air','Azerbaijan'),
	(729,'TK','THY','Turkish Airlines','Turkey'),
	(730,'T5','TUA','Turkmenistan Airlines','Turkmenistan'),
	(731,'TW','TWB','Tway Airlines','South Korea'),
	(732,'T7','TJT','Twin Jet','France'),
	(733,'VO','TYR','Tyrolean Airways','Austria'),
	(734,'PS','AUI','Ukraine International Airlines','Ukraine'),
	(735,'UF','UKM','UM Airlines','Ukraine'),
	(736,'B7','UIA','Uni Air','Taiwan'),
	(737,'UA','UAL','United Airlines','United States'),
	(738,'4H','UBD','United Airways','Bangladesh'),
	(739,'U6','SVR','Ural Airlines','Russia'),
	(740,'US','USA','US Airways','United States'),
	(741,'E1','ES2','Usa Sky Cargo','United States'),
	(742,'U5','GWY','USA3000 Airlines','United States'),
	(743,'UT','UTA','UTair Aviation','Russia'),
	(744,'HY','UZB','Uzbekistan Airways','Uzbekistan'),
	(745,'VF','VLU','Valuair','Singapore'),
	(746,'LC','VLO','Varig Log','Brazil'),
	(747,'VP','VSP','VASP','Brazil'),
	(748,'KT','VKJ','VickJet','France'),
	(749,'VN','HVN','Vietnam Airlines','Vietnam'),
	(750,'VQ','VKH','Viking Hellas','Greece'),
	(751,'NN','MOV','VIM Airlines','Russia'),
	(752,'VX','VRD','Virgin America','United States'),
	(753,'VS','VIR','Virgin Atlantic Airways','United Kingdom'),
	(754,'VA','VOZ','Virgin Australia','Australia'),
	(755,'TV','VEX','Virgin Express','Belgium'),
	(756,'VK','VGN','Virgin Nigeria Airways','Nigeria'),
	(757,'VH','VNP','Virgin Pacific','Fiji'),
	(758,'YY','VWA','Virginwings','Germany'),
	(759,'V2','RBY','Vision Airlines (V2)','United States'),
	(760,'ZG','VVM','Viva Macau','Macao'),
	(761,'5Z','VVC','VivaColombia','Colombia'),
	(762,'XF','VLK','Vladivostok Air','Russia'),
	(763,'VG','VLM','VLM Airlines','Belgium'),
	(764,'8K','K88','Voestar','Brazil'),
	(765,'VE','VLE','Volare Airlines','Italy'),
	(766,'Y4','VOI','Volaris','Mexico'),
	(767,'VI','VDA','Volga-Dnepr Airlines','Russia'),
	(768,'RG','VRN','VRG Linhas Aereas','Brazil'),
	(769,'6C','6CC','Vuela Cuba','Cuba'),
	(770,'VY','VLG','Vueling Airlines','Spain'),
	(771,'WJ','WEB','WebJet Linhas A','Brazil'),
	(772,'2W','WLC','Welcome Air','Austria'),
	(773,'PN','CHB','West Air China','China'),
	(774,'WA','WAL','Western Airlines','United States'),
	(775,'WS','WJA','WestJet','Canada'),
	(776,'WF','WIF','Widerøe','Norway'),
	(777,'IV','JET','Wind Jet','Italy'),
	(778,'IW','WON','Wings Air','Indonesia'),
	(779,'W6','WZZ','Wizz Air','Hungary'),
	(780,'8Z','WVL','Wizz Air Hungary','Bulgaria'),
	(781,'WU','WAU','Wizz Air Ukraine','Ukraine'),
	(782,'WO','WOA','World Airways','United States'),
	(783,'W1','WE1','World Experience Airline','Canada'),
	(784,'XA','XAU','XAIR USA','United States'),
	(785,'MF','CXA','Xiamen Airlines','China'),
	(786,'SE','SEU','XL Airways France','France'),
	(787,'XP','XPT','XPTO','Portugal'),
	(788,'YL','LLM','Yamal Airlines','Russia'),
	(789,'YE','YEL','Yellowtail','United States'),
	(790,'IY','IYE','Yemenia','Yemen'),
	(791,'3Q','CYH','Yunnan Airlines','China'),
	(792,'Z6','ZTT','ZABAIKAL AIRLINES','Russia'),
	(793,'ZP','ZZZ','Zabaykalskii Airlines','Russia'),
	(794,'ZN','ZNA','Zenith International Airline','Thailand'),
	(795,'Z4','OOM','Zoom Airlines','Canada');

/*!40000 ALTER TABLE `airline` ENABLE KEYS */;
UNLOCK TABLES;
